export const RECIPE_LIST = [
  {
    id: 1,
    title: "Shakshuka (North African–Style Poached Eggs in Spicy Tomato Sauce)",
    description:
      "Vegetarian shakshuka is a one-pan egg and tomato dish perfect for breakfast, lunch, or dinner.",
    image:
      "https://www.seriouseats.com/thmb/GGe7ElpAahWNo9W6c6mAx0utvFg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2016__09__20160926-shakshuka-17-a2b1d35f5ce146d1b8f5e2851e73b487.jpg",
    steps: [
      "Heat olive oil in a large, deep skillet or straight-sided sauté pan over high heat until shimmering. Add onion, red pepper, and chile and spread into an even layer. Cook, without moving, until vegetables on the bottom are deeply browned and beginning to char in spots, about 6 minutes. Stir and repeat. Continue to cook until vegetables are fully softened and spottily charred, about another 4 minutes. Add garlic and cook, stirring, until softened and fragrant, about 30 seconds. Add paprika and cumin and cook, stirring, until fragrant, about 30 seconds. Immediately add tomatoes and stir to combine (see notes). Reduce heat to a bare simmer and simmer for 10 minutes, then season to taste with salt and pepper and stir in half of cilantro or parsley.",
      "Using a large spoon, make a well near the perimeter of the pan and break an egg directly into it. Spoon a little sauce over edges of egg white to partially submerge and contain it, leaving yolk exposed. Repeat with remaining 5 eggs, working around pan as you go. Season eggs with a little salt, cover, reduce heat to lowest setting, and cook until egg whites are barely set and yolks are still runny, 5 to 8 minutes.",
      "Sprinkle with remaining cilantro or parsley, along with any of the optional toppings. Serve immediately with crusty bread.",
    ],
    ingredients: [
      "3 tablespoons (45ml) extra-virgin olive oil, plus more for drizzling",
      "1 medium onion, thinly sliced",
      "1 large red pepper (bell pepper for milder heat, or a hotter variety, such as red horned pepper, depending on your heat preference), stems, seeds, and ribs removed, thinly sliced",
      "1 fresh small hot chile (such as jalapeño, serrano, or Fresno), stems, seeds, and ribs removed, thinly sliced",
      "2 to 3 cloves garlic, thinly sliced",
      "1 1/2 tablespoons (15g) sweet Hungarian or smoked Spanish paprika",
      "2 teaspoons (8g) whole or ground cumin seeds",
      "1 (28-ounce; 800g) can whole peeled tomatoes, crushed by squeezing between your fingers or with a pastry blender",
      "Kosher salt and freshly ground black pepper",
      "Large handful minced cilantro, parsley, or a mix",
      "6 large eggs",
      "Sliced oil-cured black olives, feta cheese, and/or artichoke hearts, for serving (all optional)",
      "Crusty bread, for serving",
    ],
  },
  {
    id: 2,
    title: "Tortang Talong (Filipino Eggplant Omelette)",
    description:
      "Crispy, succulent egg-battered fried eggplant stuffed with seasoned ground pork.",
    image:
      "https://www.seriouseats.com/thmb/tDrSfqVUMb2Q1hX6oNb9-OS8ktA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210617-tortang-talong-vicky-wasik-seriouseats-seriouseats-27-1a0dcec900f94826a2f3b6b7d12fb25e.jpg",
    steps: [
      "Heat olive oil in a large, deep skillet or straight-sided sauté pan over high heat until shimmering. Add onion, red pepper, and chile and spread into an even layer. Cook, without moving, until vegetables on the bottom are deeply browned and beginning to char in spots, about 6 minutes. Stir and repeat. Continue to cook until vegetables are fully softened and spottily charred, about another 4 minutes. Add garlic and cook, stirring, until softened and fragrant, about 30 seconds. Add paprika and cumin and cook, stirring, until fragrant, about 30 seconds. Immediately add tomatoes and stir to combine (see notes). Reduce heat to a bare simmer and simmer for 10 minutes, then season to taste with salt and pepper and stir in half of cilantro or parsley.",
      "Using a large spoon, make a well near the perimeter of the pan and break an egg directly into it. Spoon a little sauce over edges of egg white to partially submerge and contain it, leaving yolk exposed. Repeat with remaining 5 eggs, working around pan as you go. Season eggs with a little salt, cover, reduce heat to lowest setting, and cook until egg whites are barely set and yolks are still runny, 5 to 8 minutes.",
      "Sprinkle with remaining cilantro or parsley, along with any of the optional toppings. Serve immediately with crusty bread.",
    ],
    ingredients: [
      "3 tablespoons (45ml) extra-virgin olive oil, plus more for drizzling",
      "1 medium onion, thinly sliced",
      "1 large red pepper (bell pepper for milder heat, or a hotter variety, such as red horned pepper, depending on your heat preference), stems, seeds, and ribs removed, thinly sliced",
      "1 fresh small hot chile (such as jalapeño, serrano, or Fresno), stems, seeds, and ribs removed, thinly sliced",
      "2 to 3 cloves garlic, thinly sliced",
      "1 1/2 tablespoons (15g) sweet Hungarian or smoked Spanish paprika",
      "2 teaspoons (8g) whole or ground cumin seeds",
      "1 (28-ounce; 800g) can whole peeled tomatoes, crushed by squeezing between your fingers or with a pastry blender",
      "Kosher salt and freshly ground black pepper",
      "Large handful minced cilantro, parsley, or a mix",
      "6 large eggs",
      "Sliced oil-cured black olives, feta cheese, and/or artichoke hearts, for serving (all optional)",
      "Crusty bread, for serving",
    ],
  },
  {
    id: 3,
    title: "Harissa (Armenian Wheat and Chicken Porridge)",
    description:
      "A porridge that's far more than the sum of its parts, with a little assist from spiced brown butter.",
    image:
      "https://www.seriouseats.com/thmb/orn7Qvs7QA1H5I70fHniUwRUbI8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20220330-harissa-andrew-janjigian-21Beauty0804_1-ebadd715236244d184de8004a4bba46b.JPG",
    steps: [
      "Heat olive oil in a large, deep skillet or straight-sided sauté pan over high heat until shimmering. Add onion, red pepper, and chile and spread into an even layer. Cook, without moving, until vegetables on the bottom are deeply browned and beginning to char in spots, about 6 minutes. Stir and repeat. Continue to cook until vegetables are fully softened and spottily charred, about another 4 minutes. Add garlic and cook, stirring, until softened and fragrant, about 30 seconds. Add paprika and cumin and cook, stirring, until fragrant, about 30 seconds. Immediately add tomatoes and stir to combine (see notes). Reduce heat to a bare simmer and simmer for 10 minutes, then season to taste with salt and pepper and stir in half of cilantro or parsley.",
      "Using a large spoon, make a well near the perimeter of the pan and break an egg directly into it. Spoon a little sauce over edges of egg white to partially submerge and contain it, leaving yolk exposed. Repeat with remaining 5 eggs, working around pan as you go. Season eggs with a little salt, cover, reduce heat to lowest setting, and cook until egg whites are barely set and yolks are still runny, 5 to 8 minutes.",
      "Sprinkle with remaining cilantro or parsley, along with any of the optional toppings. Serve immediately with crusty bread.",
    ],
    ingredients: [
      "3 tablespoons (45ml) extra-virgin olive oil, plus more for drizzling",
      "1 medium onion, thinly sliced",
      "1 large red pepper (bell pepper for milder heat, or a hotter variety, such as red horned pepper, depending on your heat preference), stems, seeds, and ribs removed, thinly sliced",
      "1 fresh small hot chile (such as jalapeño, serrano, or Fresno), stems, seeds, and ribs removed, thinly sliced",
      "2 to 3 cloves garlic, thinly sliced",
      "1 1/2 tablespoons (15g) sweet Hungarian or smoked Spanish paprika",
      "2 teaspoons (8g) whole or ground cumin seeds",
      "1 (28-ounce; 800g) can whole peeled tomatoes, crushed by squeezing between your fingers or with a pastry blender",
      "Kosher salt and freshly ground black pepper",
      "Large handful minced cilantro, parsley, or a mix",
      "6 large eggs",
      "Sliced oil-cured black olives, feta cheese, and/or artichoke hearts, for serving (all optional)",
      "Crusty bread, for serving",
    ],
  },
  {
    id: 4,
    title: "Golfeados (Venezuelan Sticky Buns)",
    description:
      "Vegetarian shakshuka is a one-pan egg and tomato dish perfect for breakfast, lunch, or dinner.",
    image:
      "https://www.seriouseats.com/thmb/bKNO2_fq5pQbWbSwbN9mjSw_OpQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2011__11__20111118-127677-Dulces-Golfeados-PRIMARY-dc857b42a0f94047b79d8dcb5807db41.jpg",
    steps: [
      "Heat olive oil in a large, deep skillet or straight-sided sauté pan over high heat until shimmering. Add onion, red pepper, and chile and spread into an even layer. Cook, without moving, until vegetables on the bottom are deeply browned and beginning to char in spots, about 6 minutes. Stir and repeat. Continue to cook until vegetables are fully softened and spottily charred, about another 4 minutes. Add garlic and cook, stirring, until softened and fragrant, about 30 seconds. Add paprika and cumin and cook, stirring, until fragrant, about 30 seconds. Immediately add tomatoes and stir to combine (see notes). Reduce heat to a bare simmer and simmer for 10 minutes, then season to taste with salt and pepper and stir in half of cilantro or parsley.",
      "Using a large spoon, make a well near the perimeter of the pan and break an egg directly into it. Spoon a little sauce over edges of egg white to partially submerge and contain it, leaving yolk exposed. Repeat with remaining 5 eggs, working around pan as you go. Season eggs with a little salt, cover, reduce heat to lowest setting, and cook until egg whites are barely set and yolks are still runny, 5 to 8 minutes.",
      "Sprinkle with remaining cilantro or parsley, along with any of the optional toppings. Serve immediately with crusty bread.",
    ],
    ingredients: [
      "3 tablespoons (45ml) extra-virgin olive oil, plus more for drizzling",
      "1 medium onion, thinly sliced",
      "1 large red pepper (bell pepper for milder heat, or a hotter variety, such as red horned pepper, depending on your heat preference), stems, seeds, and ribs removed, thinly sliced",
      "1 fresh small hot chile (such as jalapeño, serrano, or Fresno), stems, seeds, and ribs removed, thinly sliced",
      "2 to 3 cloves garlic, thinly sliced",
      "1 1/2 tablespoons (15g) sweet Hungarian or smoked Spanish paprika",
      "2 teaspoons (8g) whole or ground cumin seeds",
      "1 (28-ounce; 800g) can whole peeled tomatoes, crushed by squeezing between your fingers or with a pastry blender",
      "Kosher salt and freshly ground black pepper",
      "Large handful minced cilantro, parsley, or a mix",
      "6 large eggs",
      "Sliced oil-cured black olives, feta cheese, and/or artichoke hearts, for serving (all optional)",
      "Crusty bread, for serving",
    ],
  },
  {
    id: 5,
    title: "Jammy Fruit Bars Recipe",
    description:
      "A perfect vehicle for market-fresh blueberries, cherries, and peaches in season, or your favorite jam during those times in between.",
    image:
      "https://www.seriouseats.com/thmb/Td6BTO4phRovQIJIBjSqEqk96Z4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2019__05__20190429-fruit-oat-bars-vicky-wasik-20-3e93ffa781f74134b273a81c8a6567aa.jpg",
    steps: [
      "Heat olive oil in a large, deep skillet or straight-sided sauté pan over high heat until shimmering. Add onion, red pepper, and chile and spread into an even layer. Cook, without moving, until vegetables on the bottom are deeply browned and beginning to char in spots, about 6 minutes. Stir and repeat. Continue to cook until vegetables are fully softened and spottily charred, about another 4 minutes. Add garlic and cook, stirring, until softened and fragrant, about 30 seconds. Add paprika and cumin and cook, stirring, until fragrant, about 30 seconds. Immediately add tomatoes and stir to combine (see notes). Reduce heat to a bare simmer and simmer for 10 minutes, then season to taste with salt and pepper and stir in half of cilantro or parsley.",
      "Using a large spoon, make a well near the perimeter of the pan and break an egg directly into it. Spoon a little sauce over edges of egg white to partially submerge and contain it, leaving yolk exposed. Repeat with remaining 5 eggs, working around pan as you go. Season eggs with a little salt, cover, reduce heat to lowest setting, and cook until egg whites are barely set and yolks are still runny, 5 to 8 minutes.",
      "Sprinkle with remaining cilantro or parsley, along with any of the optional toppings. Serve immediately with crusty bread.",
    ],
    ingredients: [
      "3 tablespoons (45ml) extra-virgin olive oil, plus more for drizzling",
      "1 medium onion, thinly sliced",
      "1 large red pepper (bell pepper for milder heat, or a hotter variety, such as red horned pepper, depending on your heat preference), stems, seeds, and ribs removed, thinly sliced",
      "1 fresh small hot chile (such as jalapeño, serrano, or Fresno), stems, seeds, and ribs removed, thinly sliced",
      "2 to 3 cloves garlic, thinly sliced",
      "1 1/2 tablespoons (15g) sweet Hungarian or smoked Spanish paprika",
      "2 teaspoons (8g) whole or ground cumin seeds",
      "1 (28-ounce; 800g) can whole peeled tomatoes, crushed by squeezing between your fingers or with a pastry blender",
      "Kosher salt and freshly ground black pepper",
      "Large handful minced cilantro, parsley, or a mix",
      "6 large eggs",
      "Sliced oil-cured black olives, feta cheese, and/or artichoke hearts, for serving (all optional)",
      "Crusty bread, for serving",
    ],
  },
  {
    id: 6,
    title: "Creamy Whipped Greek Yogurt",
    description: "A light and fresh summer dessert.",
    image:
      "https://www.seriouseats.com/thmb/WyyS8GH6tuQZHXEL2-BAtP4Q32E=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__images__2017__06__20170525-whipped-greek-yogurt-vicky-wasik-8-c4eca5656dd7428ea1b9d4b6fdc465f4.jpg",
    steps: [
      "Heat olive oil in a large, deep skillet or straight-sided sauté pan over high heat until shimmering. Add onion, red pepper, and chile and spread into an even layer. Cook, without moving, until vegetables on the bottom are deeply browned and beginning to char in spots, about 6 minutes. Stir and repeat. Continue to cook until vegetables are fully softened and spottily charred, about another 4 minutes. Add garlic and cook, stirring, until softened and fragrant, about 30 seconds. Add paprika and cumin and cook, stirring, until fragrant, about 30 seconds. Immediately add tomatoes and stir to combine (see notes). Reduce heat to a bare simmer and simmer for 10 minutes, then season to taste with salt and pepper and stir in half of cilantro or parsley.",
      "Using a large spoon, make a well near the perimeter of the pan and break an egg directly into it. Spoon a little sauce over edges of egg white to partially submerge and contain it, leaving yolk exposed. Repeat with remaining 5 eggs, working around pan as you go. Season eggs with a little salt, cover, reduce heat to lowest setting, and cook until egg whites are barely set and yolks are still runny, 5 to 8 minutes.",
      "Sprinkle with remaining cilantro or parsley, along with any of the optional toppings. Serve immediately with crusty bread.",
    ],
    ingredients: [
      "3 tablespoons (45ml) extra-virgin olive oil, plus more for drizzling",
      "1 medium onion, thinly sliced",
      "1 large red pepper (bell pepper for milder heat, or a hotter variety, such as red horned pepper, depending on your heat preference), stems, seeds, and ribs removed, thinly sliced",
      "1 fresh small hot chile (such as jalapeño, serrano, or Fresno), stems, seeds, and ribs removed, thinly sliced",
      "2 to 3 cloves garlic, thinly sliced",
      "1 1/2 tablespoons (15g) sweet Hungarian or smoked Spanish paprika",
      "2 teaspoons (8g) whole or ground cumin seeds",
      "1 (28-ounce; 800g) can whole peeled tomatoes, crushed by squeezing between your fingers or with a pastry blender",
      "Kosher salt and freshly ground black pepper",
      "Large handful minced cilantro, parsley, or a mix",
      "6 large eggs",
      "Sliced oil-cured black olives, feta cheese, and/or artichoke hearts, for serving (all optional)",
      "Crusty bread, for serving",
    ],
  },
  {
    id: 7,
    title: "Classic French Omelette",
    description:
      "Our goal: an enveloping sheet of tender egg cradling a soft-scrambled interior.",
    image:
      "https://www.seriouseats.com/thmb/FWfGvovlGhKamgLyj-Jf1Tjh0IM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2016__04__20160323-french-omelet-vicky-wasik--29-4443fd8d1f5b4e359f31e384d901cefb.jpg",
    steps: [
      "Heat olive oil in a large, deep skillet or straight-sided sauté pan over high heat until shimmering. Add onion, red pepper, and chile and spread into an even layer. Cook, without moving, until vegetables on the bottom are deeply browned and beginning to char in spots, about 6 minutes. Stir and repeat. Continue to cook until vegetables are fully softened and spottily charred, about another 4 minutes. Add garlic and cook, stirring, until softened and fragrant, about 30 seconds. Add paprika and cumin and cook, stirring, until fragrant, about 30 seconds. Immediately add tomatoes and stir to combine (see notes). Reduce heat to a bare simmer and simmer for 10 minutes, then season to taste with salt and pepper and stir in half of cilantro or parsley.",
      "Using a large spoon, make a well near the perimeter of the pan and break an egg directly into it. Spoon a little sauce over edges of egg white to partially submerge and contain it, leaving yolk exposed. Repeat with remaining 5 eggs, working around pan as you go. Season eggs with a little salt, cover, reduce heat to lowest setting, and cook until egg whites are barely set and yolks are still runny, 5 to 8 minutes.",
      "Sprinkle with remaining cilantro or parsley, along with any of the optional toppings. Serve immediately with crusty bread.",
    ],
    ingredients: [
      "3 tablespoons (45ml) extra-virgin olive oil, plus more for drizzling",
      "1 medium onion, thinly sliced",
      "1 large red pepper (bell pepper for milder heat, or a hotter variety, such as red horned pepper, depending on your heat preference), stems, seeds, and ribs removed, thinly sliced",
      "1 fresh small hot chile (such as jalapeño, serrano, or Fresno), stems, seeds, and ribs removed, thinly sliced",
      "2 to 3 cloves garlic, thinly sliced",
      "1 1/2 tablespoons (15g) sweet Hungarian or smoked Spanish paprika",
      "2 teaspoons (8g) whole or ground cumin seeds",
      "1 (28-ounce; 800g) can whole peeled tomatoes, crushed by squeezing between your fingers or with a pastry blender",
      "Kosher salt and freshly ground black pepper",
      "Large handful minced cilantro, parsley, or a mix",
      "6 large eggs",
      "Sliced oil-cured black olives, feta cheese, and/or artichoke hearts, for serving (all optional)",
      "Crusty bread, for serving",
    ],
  },
  {
    id: 8,
    title: "Broccoli and Cheese Galette",
    description:
      "The secret to this creamy vegetable tart is Mornay sauce, the same cheese sauce used for a traditional mac and cheese.",
    image:
      "https://www.seriouseats.com/thmb/xfMPVVUj8Eb8IgleWSWgs0tuEfE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2019__05__20190426-savory-spring-vegetable-galettes-vicky-wasik-broccoli-onion-gruyere10-aab7ba10552c4f40b2f4d7816ea516b2.jpg",
    steps: [
      "Heat olive oil in a large, deep skillet or straight-sided sauté pan over high heat until shimmering. Add onion, red pepper, and chile and spread into an even layer. Cook, without moving, until vegetables on the bottom are deeply browned and beginning to char in spots, about 6 minutes. Stir and repeat. Continue to cook until vegetables are fully softened and spottily charred, about another 4 minutes. Add garlic and cook, stirring, until softened and fragrant, about 30 seconds. Add paprika and cumin and cook, stirring, until fragrant, about 30 seconds. Immediately add tomatoes and stir to combine (see notes). Reduce heat to a bare simmer and simmer for 10 minutes, then season to taste with salt and pepper and stir in half of cilantro or parsley.",
      "Using a large spoon, make a well near the perimeter of the pan and break an egg directly into it. Spoon a little sauce over edges of egg white to partially submerge and contain it, leaving yolk exposed. Repeat with remaining 5 eggs, working around pan as you go. Season eggs with a little salt, cover, reduce heat to lowest setting, and cook until egg whites are barely set and yolks are still runny, 5 to 8 minutes.",
      "Sprinkle with remaining cilantro or parsley, along with any of the optional toppings. Serve immediately with crusty bread.",
    ],
    ingredients: [
      "3 tablespoons (45ml) extra-virgin olive oil, plus more for drizzling",
      "1 medium onion, thinly sliced",
      "1 large red pepper (bell pepper for milder heat, or a hotter variety, such as red horned pepper, depending on your heat preference), stems, seeds, and ribs removed, thinly sliced",
      "1 fresh small hot chile (such as jalapeño, serrano, or Fresno), stems, seeds, and ribs removed, thinly sliced",
      "2 to 3 cloves garlic, thinly sliced",
      "1 1/2 tablespoons (15g) sweet Hungarian or smoked Spanish paprika",
      "2 teaspoons (8g) whole or ground cumin seeds",
      "1 (28-ounce; 800g) can whole peeled tomatoes, crushed by squeezing between your fingers or with a pastry blender",
      "Kosher salt and freshly ground black pepper",
      "Large handful minced cilantro, parsley, or a mix",
      "6 large eggs",
      "Sliced oil-cured black olives, feta cheese, and/or artichoke hearts, for serving (all optional)",
      "Crusty bread, for serving",
    ],
  },
  {
    id: 9,
    title: "Pistachio Buns",
    description:
      "A make-ahead breakfast treat that pulls all the stops for pistachio lovers.",
    image:
      "https://www.seriouseats.com/thmb/rC8UGRLIst5QcGNqbtxfMj7kgsM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2019__06__20190525-pistachio-buns-vicky-wasik-28-1500x1125-fc4d5c5a1c0d4b8bbaada925c89462ea.jpg",
    steps: [
      "Heat olive oil in a large, deep skillet or straight-sided sauté pan over high heat until shimmering. Add onion, red pepper, and chile and spread into an even layer. Cook, without moving, until vegetables on the bottom are deeply browned and beginning to char in spots, about 6 minutes. Stir and repeat. Continue to cook until vegetables are fully softened and spottily charred, about another 4 minutes. Add garlic and cook, stirring, until softened and fragrant, about 30 seconds. Add paprika and cumin and cook, stirring, until fragrant, about 30 seconds. Immediately add tomatoes and stir to combine (see notes). Reduce heat to a bare simmer and simmer for 10 minutes, then season to taste with salt and pepper and stir in half of cilantro or parsley.",
      "Using a large spoon, make a well near the perimeter of the pan and break an egg directly into it. Spoon a little sauce over edges of egg white to partially submerge and contain it, leaving yolk exposed. Repeat with remaining 5 eggs, working around pan as you go. Season eggs with a little salt, cover, reduce heat to lowest setting, and cook until egg whites are barely set and yolks are still runny, 5 to 8 minutes.",
      "Sprinkle with remaining cilantro or parsley, along with any of the optional toppings. Serve immediately with crusty bread.",
    ],
    ingredients: [
      "3 tablespoons (45ml) extra-virgin olive oil, plus more for drizzling",
      "1 medium onion, thinly sliced",
      "1 large red pepper (bell pepper for milder heat, or a hotter variety, such as red horned pepper, depending on your heat preference), stems, seeds, and ribs removed, thinly sliced",
      "1 fresh small hot chile (such as jalapeño, serrano, or Fresno), stems, seeds, and ribs removed, thinly sliced",
      "2 to 3 cloves garlic, thinly sliced",
      "1 1/2 tablespoons (15g) sweet Hungarian or smoked Spanish paprika",
      "2 teaspoons (8g) whole or ground cumin seeds",
      "1 (28-ounce; 800g) can whole peeled tomatoes, crushed by squeezing between your fingers or with a pastry blender",
      "Kosher salt and freshly ground black pepper",
      "Large handful minced cilantro, parsley, or a mix",
      "6 large eggs",
      "Sliced oil-cured black olives, feta cheese, and/or artichoke hearts, for serving (all optional)",
      "Crusty bread, for serving",
    ],
  },
  {
    id: 10,
    title: "Japanese-Style Salted Salmon (Shiozake) ",
    description: "",
    image:
      "https://www.seriouseats.com/thmb/KeVZk0JDlg5eXcBPovLnzgeV6is=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2018__07__20180620-japanese-breakfast-vicky-wasik-19-75e3d8f6b8184cce9bd67ec35dcc5afa.jpg",
    steps: [
      "Heat olive oil in a large, deep skillet or straight-sided sauté pan over high heat until shimmering. Add onion, red pepper, and chile and spread into an even layer. Cook, without moving, until vegetables on the bottom are deeply browned and beginning to char in spots, about 6 minutes. Stir and repeat. Continue to cook until vegetables are fully softened and spottily charred, about another 4 minutes. Add garlic and cook, stirring, until softened and fragrant, about 30 seconds. Add paprika and cumin and cook, stirring, until fragrant, about 30 seconds. Immediately add tomatoes and stir to combine (see notes). Reduce heat to a bare simmer and simmer for 10 minutes, then season to taste with salt and pepper and stir in half of cilantro or parsley.",
      "Using a large spoon, make a well near the perimeter of the pan and break an egg directly into it. Spoon a little sauce over edges of egg white to partially submerge and contain it, leaving yolk exposed. Repeat with remaining 5 eggs, working around pan as you go. Season eggs with a little salt, cover, reduce heat to lowest setting, and cook until egg whites are barely set and yolks are still runny, 5 to 8 minutes.",
      "Sprinkle with remaining cilantro or parsley, along with any of the optional toppings. Serve immediately with crusty bread.",
    ],
    ingredients: [
      "3 tablespoons (45ml) extra-virgin olive oil, plus more for drizzling",
      "1 medium onion, thinly sliced",
      "1 large red pepper (bell pepper for milder heat, or a hotter variety, such as red horned pepper, depending on your heat preference), stems, seeds, and ribs removed, thinly sliced",
      "1 fresh small hot chile (such as jalapeño, serrano, or Fresno), stems, seeds, and ribs removed, thinly sliced",
      "2 to 3 cloves garlic, thinly sliced",
      "1 1/2 tablespoons (15g) sweet Hungarian or smoked Spanish paprika",
      "2 teaspoons (8g) whole or ground cumin seeds",
      "1 (28-ounce; 800g) can whole peeled tomatoes, crushed by squeezing between your fingers or with a pastry blender",
      "Kosher salt and freshly ground black pepper",
      "Large handful minced cilantro, parsley, or a mix",
      "6 large eggs",
      "Sliced oil-cured black olives, feta cheese, and/or artichoke hearts, for serving (all optional)",
      "Crusty bread, for serving",
    ],
  },
];
